
name: Executar Pesquisa de Secret

on:
  workflow_dispatch:
    inputs:
      account: 
        description: 'ESCOLHA sua conta'
        required: true
        default: MASTER
        type: choice
        options:
          - Account1
          - Account2
          - Account3

      environment:
        description: 'ESCOLHA O AMBIENTE'
        required: true
        default: DEV
        type: choice
        options:
          - DEV
          - HML
          - PRD
        
      search_value:
        description: 'Valor a ser buscado nas Secrets (opcional)'
        required: false
        default: 'teste.com.br'
      az:
        description: 'Availability Zone (ex: us-east-1a, us-east-1b...)'
        required: false
        default: 'us-east-1'

env:
  DEV_ENV_NAME: "dev"
  HML_ENV_NAME: "hml"
  PRD_ENV_NAME: "prd"

jobs:
  search-secret:
    runs-on: self-hosted


    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Definindo variáveis de ambiente
        shell: bash
        run: |
          echo "Definindo Variáveis para a Conta : ${{ github.event.inputs.account }}"
          echo "Definindo variáveis para o ambiente: ${{ github.event.inputs.environment }}"

          ACCOUNT="${{ github.event.inputs.account }}"
          ENV="${{ github.event.inputs.environment }}"

          #
          # ================================
          # Account1
          # ================================
          if [[ "$ACCOUNT" == "MASTER" ]]; then
            if [[ "$ENV" == "DEV" ]]; then
              echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS }}" >> $GITHUB_ENV
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets }}" >> $GITHUB_ENV
              echo "ROLE_AWS_AUTH=${{ env.DEV_ROLE_AWS_AUTH }}" >> $GITHUB_ENV
              echo "ENV_NAME=${{ env.DEV_ENV_NAME }}" >> $GITHUB_ENV

            elif [[ "$ENV" == "HML" ]]; then
              echo "AWS_ACCESS_KEY_ID=${{ secrets. }}" >> $GITHUB_ENV
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets. }}" >> $GITHUB_ENV
              echo "ROLE_AWS_AUTH=${{ env.HML_ROLE_AWS_AUTH }}" >> $GITHUB_ENV
              echo "ENV_NAME=${{ env.HML_ENV_NAME }}" >> $GITHUB_ENV

            elif [[ "$ENV" == "PRD" ]]; then
              echo "AWS_ACCESS_KEY_ID=${{ secrets.}}" >> $GITHUB_ENV
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS }}" >> $GITHUB_ENV
              echo "ROLE_AWS_AUTH=${{ env.PRD_ROLE_AWS_AUTH }}" >> $GITHUB_ENV
              echo "ENV_NAME=${{ env.PRD_ENV_NAME }}" >> $GITHUB_ENV
            fi
          fi

          #
          # ================================
          # Account3
          # ================================
          if [[ "$ACCOUNT" == "ANALYTICS" ]]; then
            if [[ "$ENV" == "DEV" ]]; then
              echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS }}" >> $GITHUB_ENV
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS }}" >> $GITHUB_ENV
              echo "ROLE_AWS_AUTH=${{ env.DEV_ROLE_AWS_AUTH }}" >> $GITHUB_ENV
              echo "ENV_NAME=${{ env.DEV_ENV_NAME }}" >> $GITHUB_ENV

            elif [[ "$ENV" == "HML" ]]; then
              echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS}}" >> $GITHUB_ENV
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_ }}" >> $GITHUB_ENV
              echo "ROLE_AWS_AUTH=${{ env.HML_ROLE_AWS_AUTH }}" >> $GITHUB_ENV
              echo "ENV_NAME=${{ env.HML_ENV_NAME }}" >> $GITHUB_ENV

            elif [[ "$ENV" == "PRD" ]]; then
              echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS }}" >> $GITHUB_ENV
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS }}" >> $GITHUB_ENV
              echo "ROLE_AWS_AUTH=${{ env.PRD_ROLE_AWS_AUTH }}" >> $GITHUB_ENV
              echo "ENV_NAME=${{ env.PRD_ENV_NAME }}" >> $GITHUB_ENV
            fi
          fi

          #
          # ================================
          # Accoun2 (Independente do ambiente)
          # ================================
          if [[ "$ACCOUNT" == "GR.REDES" ]]; then
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.}}" >> $GITHUB_ENV
            echo "ROLE_AWS_AUTH=${{ env.PRD_ROLE_AWS_AUTH }}" >> $GITHUB_ENV
          fi

          #
          # ================================
          # VARIÁVEIS ADICIONAIS
          # ================================
          echo "SEARCH_VALUE=${{ github.event.inputs.search_value }}" >> $GITHUB_ENV
          echo "AZ=${{ github.event.inputs.az }}" >> $GITHUB_ENV

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.az }}  # 👈 variável dinâmica
          

      - name: Debug das variáveis
        run: |
          echo "-----------------------------------"
          echo "✅ Ambiente: $ENV_NAME"
          echo "🌎 Região: $REGION"
          echo "🔍 Valor de busca: $SEARCH_VALUE"
          echo "AZ: $AZ"
          echo "-----------------------------------"
          aws sts get-caller-identity
          echo "✅ AWS CLI configurado corretamente"
          echo "-----------------------------------"

      - name: Permitir execução do script
        run: chmod +x ./Search-secret/search-secret.sh 

      - name: Executar busca de Secret
        run: ./Search-secret/search-secret.sh "$SEARCH_VALUE" "$AZ"
